spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          app-client:
            provider: spring
            client-id: app-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/authorized"
            scope:
              - openid
              - profile
              - read
            client-name: app-client
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"
